script "com.livecode.widget.svgpath.__DefaultScript"
on mouseUp
   -- Toggle the hilited property when clicked
   -- set the hilited of me to (not the hilited of me)
end mouseUp

on mouseDoubleUp
end mouseDoubleUp

on mouseDown
   -- Toggle the hilited property when clicked
   --  set the hilited of me to (not the hilited of me)
end mouseDown

on mouseLeave
end mouseLeave

on mouseEnter
end mouseEnter
